### ISSUE TITLE
matchering.log.exceptions.ModuleError: 4002: Track length is exceeded in the TARGET file

### ISSUE THREAD

**Issue by reyesvicente** [sergree/matchering#21]
Hi,

I'm trying to use matchering to master a song but ran into an error. 

```
Loading and analysis
Loading the TARGET file: 'target.wav'...
The TARGET file is loaded
TARGET audio length: 99615480 samples (0:37:38)
Traceback (most recent call last):
  File "master.py", line 9, in <module>
    mg.pcm24('target24bit.wav'),
  File "/Users/highcenoid/Documents/TCSP/mastered/env/lib/python3.7/site-packages/matchering/core.py", line 53, in process
    target, target_sample_rate = check(target, target_sample_rate, config, 'target')
  File "/Users/highcenoid/Documents/TCSP/mastered/env/lib/python3.7/site-packages/matchering/checker.py", line 102, in check
    else Code.ERROR_REFERENCE_LENGTH_LENGTH_TOO_SMALL
  File "/Users/highcenoid/Documents/TCSP/mastered/env/lib/python3.7/site-packages/matchering/checker.py", line 57, in __check_length
    raise ModuleError(error_code_max)
matchering.log.exceptions.ModuleError: 4002: Track length is exceeded in the TARGET file

At first I just loaded the target and reference files, then I cut the reference file to be exactly as long as the target but was still getting the error.

**Comment by sergree** [comment]
Hello, @reyesvicente 

`TARGET audio length: 99615480 samples (0:37:38)`
But the maximum track length is 15 minutes by default.

You could change this value by editing the config:
https://github.com/sergree/matchering/blob/master/examples/edited_config.py

But this change will require more RAM to work, I can't say exactly how much.

**Comment by reyesvicente** [comment]
So it would be better if I run this on docker?

**Comment by sergree** [comment]
No. The Docker version also has this 15-minute limit, but it can't be changed in the Docker version.
